server:
  port: 8689

db:
  host: localhost
  schema: timesheetdb
  username: root
  password: P@55W0rD
  port: 3366

aws:
  resources:
    sqs:
      time-tracking-event.queue: local-hackathon-time-sheet-time-tracking-event-queue
      time-sheet-request.queue: local-hackathon-time-sheet-request-queue
    sns:
      customer-remove-data.topic: local-customer-remove-data-topic
    s3:
      time-sheet.bucket: time-sheet

customer.data.removal.aes:
  algorithm: AES/CBC/PKCS5PADDING
  password: 5110569f-7666-4c67-98e5-db8d6e1b
  iv: e2a3c25441d4f75e

spring:
  cloud:
    aws:
      endpoint: http://localhost:4566
      region:
        static: us-east-1