db:
  host: mysql
  schema: timesheetdb
  username: sys_hackathon_timesheet
  password: #defined at AWS Secrets Manager
  port: 3306

aws:
  resources:
    sqs:
      time-tracking-event.queue: prd-hackathon-time-sheet-time-tracking-event-queue
      time-sheet-request.queue: prd-hackathon-time-sheet-request-queue
    sns:
      time-tracking-event.topic: prd-customer-remove-data-topic
    s3:
      time-sheet.bucket: time-sheet