server:
  port: 8689

db:
  host: localhost
  schema: timesheetdb
  username: root
  password: P@55W0rD
  port: 3366

aws:
  resources:
    sqs:
      time-tracking-event.queue: local-hackathon-time-sheet-time-tracking-event-queue
      time-sheet-request.queue: local-hackathon-time-sheet-request-queue
    sns:
      time-tracking-event.topic: local-time-tracking-event-topic
    s3:
      time-sheet.bucket: time-sheet

spring:
  cloud:
    aws:
      endpoint: http://localhost:4566
      region:
        static: us-east-1